### ISSUE TITLE
Ship list template

### ISSUE THREAD

**Issue by barodeur** [ensiie/iaato#7]
Préparer une vue `/templates/ships` pour visualiser une liste de bateau.

**Comment by TEAM6767** [comment]
J'ai essayé avec des données que j'ai supposé, mais je n'arrive pas à le puller...

**Comment by barodeur** [comment]
Normalement t'a un bouton "Change Commits" sur ta pull request.

**Comment by barodeur** [comment]
Fixed by pull request #24
